### PR TITLE
Run code in the afterEach block after failure in an it block

### LINKED ISSUE #127: Verify and/or document afterEach runs for failing tests
Verify the current behavior of afterEach hooks for failing tests. IMO, they should still be run so cleanup code can be called. Either way the exact behavior should also be documented.

### LINKED ISSUE #148: afterEach doesn't run if it block fails
afterEach is usually used for cleanup/teardown. If the `it` block fails however, the `afterEach` cycle won't invoke.

### PR DESCRIPTION
**Pull request by ConMur**
Modifies the TestRunner to continue running the tests after a failure in the it block.  Any errors reported after the it block are appended to the error message with the line "While cleaning up the failed test another error was found" separating them.

- [x] Code Style: Match the existing code! (I tried to follow the style.  If there are changes I should make let me know!)
- [x] Changelog: Add an entry to CHANGELOG.md
- [x] Luacheck: Run Luacheck on your code, no warnings allowed!
- [x] Tests: They all need to pass!

Fixes #148 and fixes #127

### CODE REVIEW

**Comment by ConMur** [comment]
Comment to get the CLA bot to run

**Comment by ConMur** [comment]
I have read the CLA Document and I hereby sign the CLA

File: test/roblox-cli.sh [hunk 1]
```diff
@@ -15,4 +15,4 @@ else
 fi
 
 rojo build test-place.project.json -o TestPlace.rbxlx
-roblox-cli run --load.place TestPlace.rbxlx --assetFolder "$CONTENT"
\ No newline at end of file
+robloxdev-cli run --load.place TestPlace.rbxlx --assetFolder "$CONTENT"
```
Comment (benbrimeyer) [inline test/roblox-cli.sh:18]: Why set to robloxdev-cli? Since its a public repository we may want to try to keep this as roblox-cli if possible

**Review by MagiMaster — APPROVED** [review]

**Review by benbrimeyer — CHANGES_REQUESTED** [review]

**Review by benbrimeyer — APPROVED** [review]

**Comment by ConMur** [comment]
Modifies the TestRunner to continue running the tests after a failure in the it block. Any errors reported after the it block are appended to the error message with the line "While cleaning up the failed test another error was found" separating them.
